name: RLBind_env
channels:
  - pytorch
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
  - conda-forge
  - defaults
dependencies:
  - aiohttp=3.7.4.post0=py37hcc03f2d_1
  - arrow-cpp=9.0.0=py37hd749cc5_7_cpu
  - async-timeout=3.0.1=py_1000
  - attrs=24.2.0=pyh71513ae_0
  - aws-c-cal=0.5.11=he19cf47_0
  - aws-c-common=0.6.2=h8ffe710_0
  - aws-c-event-stream=0.2.7=h70e1b0c_13
  - aws-c-io=0.10.5=h2fe331c_0
  - aws-checksums=0.1.11=h1e232aa_7
  - aws-sdk-cpp=1.8.186=h93d3aa3_4
  - blas=1.0=mkl
  - brotli-python=1.0.9=py37hf2a7229_7
  - bzip2=1.0.8=h2466b09_7
  - c-ares=1.34.3=h2466b09_1
  - ca-certificates=2024.8.30=h56e8100_0
  - certifi=2024.8.30=pyhd8ed1ab_0
  - chardet=4.0.0=py37h03978a9_3
  - charset-normalizer=3.4.0=pyhd8ed1ab_0
  - click=8.1.3=py37h03978a9_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - cudatoolkit=11.1.1=hb074779_13
  - cudnn=6.0=0
  - dataclasses=0.8=pyhc8e2a94_3
  - datasets=2.13.1=pyhd8ed1ab_0
  - dill=0.3.6=pyhd8ed1ab_1
  - filelock=3.16.1=pyhd8ed1ab_0
  - freetype=2.12.1=hdaf720e_2
  - fsspec=2023.1.0=pyhd8ed1ab_0
  - gflags=2.2.2=he0c23c2_1005
  - glog=0.6.0=h4797de2_0
  - grpc-cpp=1.47.1=h535cfc9_7
  - huggingface_hub=0.16.4=pyhd8ed1ab_0
  - icc_rt=2022.1.0=h6049295_2
  - idna=3.10=pyhd8ed1ab_0
  - importlib-metadata=4.11.4=py37h03978a9_0
  - importlib_metadata=4.11.4=hd8ed1ab_0
  - intel-openmp=2023.1.0=h59b6b97_46320
  - joblib=1.3.2=pyhd8ed1ab_0
  - jpeg=9b=hb83a4c4_2
  - krb5=1.20.1=h6609f42_0
  - lcms2=2.12=h83e58a3_0
  - lerc=4.0.0=h63175ca_0
  - libabseil=20220623.0=cxx17_h1a56200_6
  - libblas=3.8.0=20_mkl
  - libbrotlicommon=1.0.9=hcfcfb64_9
  - libbrotlidec=1.0.9=hcfcfb64_9
  - libbrotlienc=1.0.9=hcfcfb64_9
  - libcblas=3.8.0=20_mkl
  - libcrc32c=1.1.2=h0e60522_0
  - libcurl=8.1.2=h68f0423_0
  - libdeflate=1.14=hcfcfb64_0
  - libgoogle-cloud=2.2.0=hc8dde07_1
  - liblapack=3.8.0=20_mkl
  - libpng=1.6.44=h3ca93ac_0
  - libprotobuf=3.21.12=h12be248_2
  - libssh2=1.10.0=h680486a_3
  - libthrift=0.16.0=h9f558f2_2
  - libtiff=4.5.0=h8a3f274_0
  - libutf8proc=2.8.0=h82a8f57_0
  - libuv=1.48.0=hcfcfb64_0
  - libwebp=1.4.0=h2466b09_0
  - libwebp-base=1.4.0=hcfcfb64_0
  - libxcb=1.13=hcd874cb_1004
  - libzlib=1.3.1=h2466b09_1
  - lz4-c=1.9.4=hcfcfb64_0
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - mkl=2020.2=256
  - mkl-service=2.3.0=py37h4ab8f01_2
  - mkl_fft=1.0.6=py37h25d0782_0
  - mkl_random=1.0.2=py37hb452f36_0
  - msys2-conda-epoch=20160418=1
  - multidict=6.0.2=py37hcc03f2d_1
  - multiprocess=0.70.14=py37h51bd9d9_0
  - ninja=1.12.1=hc790b64_0
  - numpy=1.20.3=py37hcbcd69c_0
  - numpy-base=1.18.5=py37hc3f5095_0
  - openjpeg=2.5.0=ha2aaf27_2
  - openssl=1.1.1w=hcfcfb64_0
  - packaging=23.2=pyhd8ed1ab_0
  - pandas=1.2.5=py37h90003fb_0
  - parquet-cpp=1.5.1=2
  - pillow=9.3.0=py37hdc2b20a_1
  - pip=22.3.1=py37haa95532_0
  - pthread-stubs=0.4=hcd874cb_1001
  - pyarrow=9.0.0=py37h8d229b1_7_cpu
  - pysocks=1.7.1=py37h03978a9_5
  - python=3.7.12=h7840368_100_cpython
  - python-dateutil=2.9.0=pyhd8ed1ab_0
  - python-xxhash=3.0.0=py37hcc03f2d_1
  - python_abi=3.7=4_cp37m
  - pytorch=1.9.1=py3.7_cuda11.1_cudnn8_0
  - pytz=2024.2=pyhd8ed1ab_0
  - pyyaml=6.0=py37hcc03f2d_4
  - re2=2022.06.01=h0e60522_1
  - regex=2022.9.13=py37h51bd9d9_0
  - requests=2.32.2=pyhd8ed1ab_0
  - responses=0.18.0=pyhd8ed1ab_0
  - sacremoses=0.0.53=pyhd8ed1ab_0
  - scikit-learn=0.24.2=py37ha78be43_1
  - scipy=1.7.3=py37hb6553fb_0
  - setuptools=59.8.0=py37h03978a9_1
  - six=1.16.0=pyhd3eb1b0_1
  - snappy=1.1.10=hfb803bf_1
  - sqlite=3.45.3=h2bbff1b_0
  - threadpoolctl=3.1.0=pyh8a188c0_0
  - tk=8.6.13=h5226925_1
  - tokenizers=0.13.1=py37h5a64036_0
  - torchvision=0.10.1=py37_cu111
  - tqdm=4.67.1=pyhd8ed1ab_0
  - transformers=4.29.2=pyhd8ed1ab_0
  - typing-extensions=4.7.1=hd8ed1ab_0
  - typing_extensions=4.7.1=pyha770c72_0
  - ucrt=10.0.22621.0=h57928b3_0
  - urllib3=2.2.1=pyhd8ed1ab_0
  - vc=14.40=h2eaa2aa_1
  - vc14_runtime=14.40.33810=ha82c5b3_21
  - vs2015_runtime=14.40.33810=h3bf8584_21
  - wheel=0.38.4=py37haa95532_0
  - win_inet_pton=1.1.0=pyh7428d3b_7
  - wincertstore=0.2=py37haa95532_2
  - xorg-libxau=1.0.11=hcd874cb_0
  - xorg-libxdmcp=1.1.3=hcd874cb_0
  - xxhash=0.8.0=h8ffe710_3
  - xz=5.2.6=h8d14728_0
  - yaml=0.2.5=h8ffe710_2
  - yarl=1.7.2=py37hcc03f2d_2
  - zipp=3.15.0=pyhd8ed1ab_0
  - zlib=1.3.1=h2466b09_1
  - zstd=1.5.6=h0ea2cb4_0
  - pip:
      - future==1.0.0
prefix: E:\Anaconda\envs\RLBind_env
